---
kind: Service
apiVersion: v1
metadata:
  name: elk-logstash
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: elk-logstash
    stack: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0